// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Article struct {
	ID          uuid.UUID
	Url         string
	Title       string
	Content     string
	Catagory    string
	ImageUrl    sql.NullString
	CreatedAt   time.Time
	PublishedAt time.Time
}
